theme: minima
title: Bollocks 
author: Grandpa Bugbear 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  There are so many awesome things about this non-blog. Wow!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
